from list import List
from elemList import ElemList

newlist = List()
elem = ElemList(1)
elem2 = ElemList(2)
elem3 = ElemList(3)
elem4 = ElemList(4)
elem5 = ElemList(5)
elem6 = ElemList(6)
elem7 = ElemList(7)
elem8 = ElemList(8)
elem9 = ElemList(9)
elem10 = ElemList(10)

newlist.addFront(elem2)
newlist.addFront(elem3)
newlist.addFront(elem4)
newlist.addFront(elem5)
newlist.addFront(elem6)
newlist.addFront(elem7)
newlist.addFront(elem8)
newlist.addFront(elem9)
newlist.addFront(elem10)
newlist.addBack(elem)
print("Old List:")
newlist.printList()
newlist.revers()
print("New List:")
newlist.printList()
newlist.pickbyindex()